# Nombre del pipeline que aparecerá en la pestaña "Actions" de GitHub
name: Build Frontend Service

# Define cuándo se debe ejecutar este pipeline
on:
  # Se ejecutará cada vez que se haga un push a la rama main
  push:
    branches: [ "main" ]
    # Solo si hay cambios dentro de la carpeta del frontend
    paths: [ 'src/frontend/**' ]

# Define los trabajos (jobs) que se ejecutarán
jobs:
  build-and-push:
    # El pipeline correrá en una máquina virtual de Ubuntu proporcionada por GitHub
    runs-on: ubuntu-latest

    # Los pasos que ejecutará el pipeline
    steps:
    # Paso 1: Descargar el código de tu repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Iniciar sesión en el Registro de Contenedores de GitHub (GHCR)
    # Usa el token que guardamos en los "Secrets" del repositorio
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}

    # Paso 3: Construir la imagen de Docker
    # La construye usando el Dockerfile que está en la carpeta del frontend
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/SoniaGuevara/frontend:latest ./src/frontend

    # Paso 4: Subir la imagen de Docker a GHCR
    - name: Push Docker image
      run: |
        docker push ghcr.io/SoniaGuevara/frontend:latest
